<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
	 <Company>Acumatica</Company>
    <Copyright>Copyright © 2005-2025 Acumatica, Inc. All rights reserved.</Copyright>
    <PackageProjectUrl>https://github.com/Acumatica/UnitTestExamples</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Acumatica/UnitTestExamples</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="FluentAssertions" Version="6.10.0" />
	<PackageReference Include="Moq" Version="4.20.72" />
	<PackageReference Include="System.ValueTuple" Version="4.6.1" />
	<PackageReference Include="xunit.abstractions" Version="2.0.3" />
	<PackageReference Include="xunit.assert" Version="2.4.1" />
	<PackageReference Include="xunit.core" Version="2.4.1" />
	<PackageReference Include="xunit.extensibility.core" Version="2.4.1" />
	<PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Bogus" Version="34.0.2" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Autofac">
      <HintPath>..\..\..\Acumatica Sites\26r1\Bin\Autofac.dll</HintPath>
    </Reference>
    <Reference Include="PX.Common">
      <HintPath>..\..\..\Acumatica Sites\26r1\Bin\PX.Common.dll</HintPath>
    </Reference>
    <Reference Include="PX.Common.Std">
      <HintPath>..\..\..\..\..\..\Acumatica Sites\26r1\Bin\PX.Common.Std.dll</HintPath>
    </Reference>
    <Reference Include="PX.Data">
      <HintPath>..\..\..\..\..\..\Acumatica Sites\26r1\Bin\PX.Data.dll</HintPath>
    </Reference>
    <Reference Include="PX.Data.BQL.Fluent">
      <HintPath>..\..\..\..\..\..\Acumatica Sites\26r1\Bin\PX.Data.BQL.Fluent.dll</HintPath>
    </Reference>
    <Reference Include="PX.Objects">
      <HintPath>..\..\..\..\..\..\Acumatica Sites\26r1\Bin\PX.Objects.dll</HintPath>
    </Reference>
    <Reference Include="PX.Tests.Unit">
      <HintPath>..\..\..\Acumatica Installers\26.100.0175\Acumatica ERP\UnitTesting\PX.Tests.Unit.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.configuration" />
    <Reference Include="System.Core" />
    <Reference Include="System.Net.Http.WebRequest" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Web" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
</Project>
